<?php require_once __DIR__ . '/config/app.php'; ?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="โครงการเว็บไซต์เพื่อการศึกษา OMODA & JAECOO จังหวัดตรัง"><title>OMODA & JAECOO Trang · Educational Project</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="assets/css/site.css"></head>
<body>
<div class="notice" id="notice"><div><b>เว็บไซต์ต้นแบบเพื่อการศึกษา</b><p>จัดทำเพื่อช่วยเหลือสถานประกอบการจังหวัดตรัง ไม่ใช่เว็บไซต์อย่างเป็นทางการและไม่มีวัตถุประสงค์ทางการค้า</p><button type="button" data-close-notice>รับทราบและเข้าสู่เว็บไซต์</button></div></div>
<header class="nav"><a class="brand" href="#home"><img src="cars/brand-logo.svg" alt="OMODA & JAECOO"><span>TRANG · EDUCATIONAL PROJECT</span></a><button class="nav-toggle" aria-label="เปิดเมนู">☰</button><nav><a class="model-link" href="#models">รุ่นรถ</a><a href="#experience">สัมผัสประสบการณ์</a><a href="#booking">ทดลองขับ</a><a href="https://www.omodajaecoo.co.th/th" target="_blank" rel="noopener">เว็บไซต์ทางการ</a><a class="staff-link" href="admin/login.php">เจ้าหน้าที่</a></nav></header>
<main id="home">
<section class="hero"><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow">NEW ENERGY · NEW ECO · TRANG</span><h1>DRIVE<br><em>YOUR FUTURE</em></h1><p>สำรวจยนตรกรรมพลังงานใหม่ที่ออกแบบเพื่อทุกเส้นทาง</p><a class="primary" href="#models">ค้นพบรุ่นรถ</a></div><div class="hero-model">JAECOO 6T EV<br><small>URBAN OFF-ROAD EV</small></div></section>
<section class="models" id="models"><div class="section-heading"><span>DISCOVER</span><h2>เลือกรถที่เป็นคุณ</h2></div><div class="model-tabs" role="tablist">
<button class="active" data-model="j5">JAECOO 5 EV</button><button data-model="c5">OMODA C5 EV</button><button data-model="j6t">JAECOO 6T EV</button><button data-model="reev">JAECOO 6T REEV</button></div>
<div class="car-stage"><div class="car-info"><span id="car-kind">PURE ELECTRIC</span><h3 id="car-name">JAECOO 5 EV</h3><p id="car-copy">อิสระของการขับขี่ไฟฟ้าในดีไซน์ SUV เหนือระดับ</p><div class="specs"><div><b id="car-range">461</b><small>กม. ระยะทางสูงสุด</small></div><div><b id="car-power">155</b><small>kW กำลังสูงสุด</small></div></div></div><div class="car-visual"><img id="car-image" src="cars/j5-green.png" alt="JAECOO 5 EV"><div class="colors" aria-label="เลือกสีรถ"><button class="active" data-color="green" aria-label="สีเขียว"></button><button data-color="white" aria-label="สีขาว"></button><button data-color="black" aria-label="สีดำ"></button></div></div></div>
</section>
<section class="experience" id="experience"><img id="interior-image" src="cars/interior-premium.jpg" alt="ภายในห้องโดยสาร"><div><span class="eyebrow">IMMERSIVE CABIN</span><h2>พื้นที่ที่ออกแบบ<br>รอบตัวคุณ</h2><p>สัมผัสห้องโดยสารพรีเมียม เทคโนโลยีอัจฉริยะ และความสบายในทุกการเดินทาง</p><button class="ghost" type="button" data-interior>สลับมุมมองภายใน</button></div></section>
<section class="booking" id="booking"><div><span class="eyebrow">BOOK A TEST DRIVE</span><h2>พร้อมสัมผัส<br>ด้วยตัวคุณเองหรือยัง?</h2><p>ส่งข้อมูลถึงทีมงานจังหวัดตรัง ระบบจะออกหมายเลขอ้างอิงให้ทันที</p></div><form id="booking-form" action="api/create_booking.php" method="post"><div class="form-grid"><label>ชื่อ-นามสกุล<input name="customer_name" required maxlength="120"></label><label>เบอร์โทรศัพท์<input name="phone" type="tel" required pattern="[0-9+ -]{9,20}"></label><label>อีเมล<input name="email" type="email" maxlength="160"></label><label>รุ่นรถ<select name="model" required><option value="JAECOO 5 EV">JAECOO 5 EV</option><option value="OMODA C5 EV">OMODA C5 EV</option><option value="JAECOO 6T EV">JAECOO 6T EV</option><option value="JAECOO 6T REEV">JAECOO 6T REEV</option></select></label><label>วันที่สะดวก<input name="appointment_date" type="date" required min="<?= date('Y-m-d') ?>"></label><label>ช่วงเวลา<select name="appointment_time" required><option value="09:00">09:00</option><option value="11:00">11:00</option><option value="13:00">13:00</option><option value="15:00">15:00</option></select></label></div><label>ข้อความเพิ่มเติม<textarea name="message" maxlength="1000"></textarea></label><label class="consent"><input type="checkbox" name="consent" value="1" required> ยินยอมให้ติดต่อกลับเพื่อดำเนินการนัดหมาย</label><button class="primary submit" type="submit">ยืนยันการจองทดลองขับ</button><div id="form-result" role="status"></div></form></section>
</main><footer><img src="cars/brand-logo.svg" alt=""><p>เว็บไซต์ต้นแบบเพื่อการศึกษา · จังหวัดตรัง</p><a href="https://www.omodajaecoo.co.th/th" target="_blank" rel="noopener">เยี่ยมชมเว็บไซต์ทางการ ↗</a></footer><script src="assets/js/site.js"></script></body></html>

