<?php
declare(strict_types=1); require_once __DIR__ . '/includes/auth.php'; require_login();
$stats = db()->query("SELECT COUNT(*) total, SUM(status='new') new_count, SUM(status='confirmed') booked_count, SUM(status='completed') sold_count FROM leads")->fetch();
$models = db()->query("SELECT model, COUNT(*) total, SUM(status='confirmed') booked, SUM(status='completed') sold FROM leads GROUP BY model ORDER BY total DESC")->fetchAll();
$recent = db()->query("SELECT id, reference_no, customer_name, model, status, appointment_date FROM leads ORDER BY created_at DESC LIMIT 8")->fetchAll();
$pageTitle='ภาพรวมการจอง'; require __DIR__.'/includes/header.php';
?><section class="stats"><div class="stat"><span>ผู้สนใจทั้งหมด</span><b><?= (int)$stats['total'] ?></b></div><div class="stat"><span>รายการใหม่</span><b><?= (int)$stats['new_count'] ?></b></div><div class="stat"><span>ยืนยันการจอง</span><b><?= (int)$stats['booked_count'] ?></b></div><div class="stat"><span>ขายสำเร็จ</span><b><?= (int)$stats['sold_count'] ?></b></div></section>
<div class="dashboard-grid"><section class="panel"><h2>ยอดจองและยอดขายตามรุ่น</h2><?php if(!$models):?><div class="empty">ยังไม่มีข้อมูลจากฐานข้อมูล</div><?php endif?><?php foreach($models as $m):$max=max(1,(int)$stats['total']);?><div class="model-row"><div><b><?=e($m['model'])?></b><div class="bar"><i style="width:<?=round(((int)$m['total']/$max)*100)?>%"></i></div></div><span>จอง<br><b><?=(int)$m['booked']?></b></span><span>ขาย<br><b><?=(int)$m['sold']?></b></span></div><?php endforeach?></section><section class="panel"><h2>รายการล่าสุด</h2><?php foreach($recent as $lead):?><div class="model-row"><div><b><?=e($lead['customer_name'])?></b><small><?=e($lead['model'])?> · <?=e($lead['reference_no'])?></small></div><span class="status <?=e($lead['status'])?>"><?=e(status_label($lead['status']))?></span><a class="btn secondary" href="lead-edit.php?id=<?=(int)$lead['id']?>">ดู</a></div><?php endforeach?></section></div>
<?php require __DIR__.'/includes/footer.php'; ?>
