<?php
declare(strict_types=1);require_once __DIR__.'/includes/auth.php';require_login();
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['delete_id'])){verify_csrf();$stmt=db()->prepare('DELETE FROM leads WHERE id=?');$stmt->execute([(int)$_POST['delete_id']]);header('Location:leads.php?deleted=1');exit;}
$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'');$page=max(1,(int)($_GET['page']??1));$limit=15;$where=[];$args=[];
if($q!==''){$where[]='(customer_name LIKE ? OR phone LIKE ? OR reference_no LIKE ? OR model LIKE ?)';$like="%{$q}%";$args=array_merge($args,[$like,$like,$like,$like]);}
if(in_array($status,['new','contacted','confirmed','completed','cancelled'],true)){$where[]='status=?';$args[]=$status;}$sqlWhere=$where?' WHERE '.implode(' AND ',$where):'';
$count=db()->prepare('SELECT COUNT(*) FROM leads'.$sqlWhere);$count->execute($args);$total=(int)$count->fetchColumn();$offset=($page-1)*$limit;$stmt=db()->prepare('SELECT * FROM leads'.$sqlWhere.' ORDER BY created_at DESC LIMIT '.$limit.' OFFSET '.$offset);$stmt->execute($args);$leads=$stmt->fetchAll();$pages=max(1,(int)ceil($total/$limit));
$pageTitle='รายการผู้สนใจ';require __DIR__.'/includes/header.php';
?><form class="table-tools" method="get"><input name="q" value="<?=e($q)?>" placeholder="ค้นหาชื่อ เบอร์โทร รุ่น หรือเลขอ้างอิง"><select name="status"><option value="">ทุกสถานะ</option><?php foreach(['new'=>'ใหม่','contacted'=>'ติดต่อแล้ว','confirmed'=>'จองแล้ว','completed'=>'ขายแล้ว','cancelled'=>'ยกเลิก'] as $v=>$label):?><option value="<?=$v?>" <?=$status===$v?'selected':''?>><?=$label?></option><?php endforeach?></select><button class="btn">ค้นหา</button></form>
<?php if(isset($_GET['deleted'])):?><div class="success">ลบข้อมูลแล้ว</div><?php endif?><div class="table-wrap"><table><thead><tr><th>เลขอ้างอิง</th><th>ลูกค้า</th><th>โทรศัพท์</th><th>รุ่นรถ</th><th>นัดหมาย</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody><?php foreach($leads as $lead):?><tr><td><?=e($lead['reference_no'])?></td><td><?=e($lead['customer_name'])?></td><td><?=e($lead['phone'])?></td><td><?=e($lead['model'])?></td><td><?=e(thai_date($lead['appointment_date']))?> <?=e(substr($lead['appointment_time'],0,5))?></td><td><span class="status <?=e($lead['status'])?>"><?=e(status_label($lead['status']))?></span></td><td><div class="actions"><a class="btn secondary" href="lead-edit.php?id=<?=(int)$lead['id']?>">แก้ไข</a><form method="post" onsubmit="return confirm('ยืนยันการลบรายการนี้?')"><?=csrf_field()?><input type="hidden" name="delete_id" value="<?=(int)$lead['id']?>"><button class="btn danger">ลบ</button></form></div></td></tr><?php endforeach?><?php if(!$leads):?><tr><td colspan="7" class="empty">ไม่พบข้อมูล</td></tr><?php endif?></tbody></table></div><div class="pagination"><?php for($i=1;$i<=$pages;$i++):?><a class="<?=$i===$page?'active':''?>" href="?q=<?=urlencode($q)?>&status=<?=urlencode($status)?>&page=<?=$i?>"><?=$i?></a><?php endfor?></div>
<?php require __DIR__.'/includes/footer.php'; ?>
