<?php
declare(strict_types=1);require_once __DIR__.'/includes/auth.php';require_admin();$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
 if(isset($_POST['toggle_id'])){$id=(int)$_POST['toggle_id'];if($id===(int)$_SESSION['staff_id'])$error='ไม่สามารถปิดบัญชีที่กำลังใช้งาน';else{$stmt=db()->prepare('UPDATE staff SET is_active=NOT is_active WHERE id=?');$stmt->execute([$id]);$message='อัปเดตสถานะแล้ว';}}
 else{$code=strtoupper(trim((string)($_POST['staff_code']??'')));$name=trim((string)($_POST['name']??''));$password=(string)($_POST['password']??'');$secret=(string)($_POST['secret_code']??'');$role=in_array($_POST['role']??'', ['admin','staff'],true)?$_POST['role']:'staff';if(!preg_match('/^[A-Z0-9_-]{3,30}$/',$code)||mb_strlen($name)<2||strlen($password)<8||!preg_match('/^\d{6}$/',$secret))$error='ตรวจสอบข้อมูล: รหัสเจ้าหน้าที่ 3 ตัวขึ้นไป รหัสผ่านอย่างน้อย 8 ตัว และรหัสลับ 6 หลัก';else try{$stmt=db()->prepare('INSERT INTO staff(staff_code,name,password_hash,secret_code_hash,role) VALUES(?,?,?,?,?)');$stmt->execute([$code,$name,password_hash($password,PASSWORD_DEFAULT),password_hash($secret,PASSWORD_DEFAULT),$role]);$message='เพิ่มเจ้าหน้าที่แล้ว';}catch(PDOException $e){$error='รหัสเจ้าหน้าที่ซ้ำหรือบันทึกไม่ได้';}}
}
$staff=db()->query('SELECT id,staff_code,name,role,is_active,last_login_at,created_at FROM staff ORDER BY created_at DESC')->fetchAll();$pageTitle='จัดการเจ้าหน้าที่';require __DIR__.'/includes/header.php';
?><div class="dashboard-grid"><form class="form-card" method="post"><?=csrf_field()?><?php if($message):?><div class="success"><?=e($message)?></div><?php endif?><?php if($error):?><div class="error"><?=e($error)?></div><?php endif?><h2>เพิ่มเจ้าหน้าที่</h2><label class="field">รหัสเจ้าหน้าที่<input name="staff_code" required maxlength="30" placeholder="STF001"></label><label class="field">ชื่อ<input name="name" required maxlength="120"></label><label class="field">รหัสผ่าน<input name="password" type="password" required minlength="8"></label><label class="field">รหัสลับ 6 หลัก<input name="secret_code" type="password" inputmode="numeric" pattern="[0-9]{6}" required></label><label class="field">สิทธิ์<select name="role"><option value="staff">เจ้าหน้าที่</option><option value="admin">ผู้ดูแลระบบ</option></select></label><button class="btn">เพิ่มบัญชี</button></form><section class="panel"><h2>บัญชีทั้งหมด</h2><?php foreach($staff as $s):?><div class="model-row"><div><b><?=e($s['name'])?></b><small><?=e($s['staff_code'])?> · <?=e($s['role'])?></small></div><span><?=$s['is_active']?'ใช้งาน':'ปิด'?></span><form method="post"><?=csrf_field()?><input type="hidden" name="toggle_id" value="<?=(int)$s['id']?>"><button class="btn secondary">สลับ</button></form></div><?php endforeach?></section></div><?php require __DIR__.'/includes/footer.php';?>

